'''
Lib dos principais vetores usados no programa principal
'''

bonecos = [
    'duelist',
    'marauder',
    'ranger',
    'scion',
    'shadow',
    'templar',
    'witch'
]

ascensoes = {
    'duelist': ['slayer', 'champion', 'gladiator'],
    'marauder': ['chieftain', 'berserker', 'juggernaut'],
    'ranger': ['raider', 'pathfinder', 'deadeye'],
    'scion': ['ascendant'],
    'shadow': ['saboteur', 'trickster', 'assassin'],
    'templar': ['hierophant', 'inquisitor', 'guardian'],
    'witch': ['necromancer', 'occultist', 'elementalist'],
}

titles = {
    'duelist': 'handsome ',
    'marauder': 'brave ',
    'ranger': 'ferocious ',
    'scion': 'bitter ',
    'shadow': 'tricky ',
    'templar': 'faithful ',
    'witch': 'insane '
}

skills = [
    "Abyssal Cry",
    "Ancestral Warchief",
    "Animate Guardian",
    "Animate Weapon",
    "Arc",
    "Arctic Breath",
    "Artillery Ballista",
    "Summon Raging Spirit",
    "Ball Lightning",
    "Barrage",
    "Bear Trap",
    "Blade Vortex",
    "Bladefall",
    "Bladestorm",
    "Blast Rain",
    "Blight",
    "Perforate",
    "Unearth",
    "Burning Arrow",
    "Armageddon Brand",
    "Chain Hook",
    "Death Aura",
    "Blade Flurry",
    "Charged Dash",
    "Cleave",
    "Kinetic Blast",
    "Cobra Lash",
    "Icicle Mine",
    "Cold Snap",
    "Storm Brand",
    "Consecrated Path",
    "Contagion",
    "Cremation",
    "Bodyswap",
    "Plague Bearer",
    "Cyclone",
    "Dark Pact",
    "Bane",
    "Detonate Dead",
    "Discharge",
    "Scorching Ray",
    "Divine Ire",
    "Dominating Blow",
    "Lacerate",
    "Double Strike",
    "Dual Strike",
    "Earthquake",
    "Elemental Hit",
    "Tectonic Slam",
    "Ensnaring Arrow",
    "Essence Drain",
    "Ethereal Knives",
    "Incinerate",
    "Explosive Arrow",
    "Fire Trap",
    "Fireball",
    "Firestorm",
    "Flame Dash",
    "Holy Flame Totem",
    "Flame Surge",
    "Flameblast",
    "Flamethrower Trap",
    "Flicker Strike",
    "Freezing Pulse",
    "Frenzy",
    "Frost Blades",
    "Frostbolt",
    "Vortex",
    "Frost Bomb",
    "Winter Orb",
    "Glacial Cascade",
    "Glacial Hammer",
    "Ground Slam",
    "Heavy Strike",
    "Herald of Agony",
    "Herald of Ice",
    "Herald of Purity",
    "Herald of Thunder",
    "Ice Crash",
    "Frostblink",
    "Ice Nova",
    "Ice Shot",
    "Siphoning Trap",
    "Ice Spear",
    "Ice Trap",
    "Icestorm",
    "Infernal Blow",
    "Lancing Steel",
    "Leap Slam",
    "Lightning Arrow",
    "Stormblast Mine",
    "Lightning Strike",
    "Lightning Tendrils",
    "Lightning Spire Trap",
    "Lightning Trap",
    "Lightning Warp",
    "Magma Orb",
    "Pestilent Strike",
    "Molten Strike",
    "Blade Vortex",
    "Shield Charge",
    "Shock Nova",
    "Orb of Storms",
    "Seismic Trap",
    "Caustic Arrow",
    "Power Siphon",
    "Puncture",
    "Wave of Conviction",
    "Rain of Arrows",
    "Toxic Rain",
    "Raise Spectre",
    "Raise Zombie",
    "Reave",
    "Reckoning",
    "Abberath's Fury",
    "Righteous Fire",
    "Purifying Flame",
    "Scourge Arrow",
    "Searing Bond",
    "Shattering Steel",
    "Shock Nova",
    "Shockwave Totem",
    "Shrapnel Ballista",
    "Galvanic Arrow",
    "Explosive Trap",
    "Siege Ballista",
    "Smite",
    "Venom Gyre",
    "Soulrend",
    "Spark",
    "Split Arrow",
    "Static Strike",
    "Storm Burst",
    "Storm Call",
    "Summon Carrion Golem",
    "Summon Chaos Golem",
    "Summon Flame Golem",
    "Summon Ice Golem",
    "Summon Lightning Golem",
    "Summon Raging Spirit",
    "Summon Holy Relic",
    "Summon Stone Golem",
    "Summon Skeletons",
    "Sunder",
    "Shockwave",
    "Sweep",
    "Spectral Shield Throw",
    "Spectral Throw",
    "Tornado Shot",
    "Ancestral Protector",
    "Doryani's Touch",
    "Animate Weapon",
    "Summon Phantasm",
    "Vengeance",
    "Vigilant Strike",
    "Viper Strike",
    "Whirling Blades",
    "Wild Strike",
    "Wrath"
]